name: Gemini_Final_Cloud
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descarga_Directa
        run: |
          pip install gdown
          # Descargamos tu proyecto
          gdown --id 1ZUzXrJ1dUU_5cQzyOO6-y-oH_wEpJlda
          unzip grabpack_in_godot.zip
          
          # Descargamos el motor Godot con CURL (es mas estable)
          curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux_x86_64.zip
          curl -L -o templates.tpz https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          
          # Buscamos donde esta el proyecto
          D=$(find . -name "project.godot" -exec dirname {} \; | head -n 1)
          echo "PROJ_PATH=$D" >> $GITHUB_ENV

      - name: Generar_APK
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: ./godot.zip
          godot_export_templates_download_url: ./templates.tpz
          relative_project_path: ${{ env.PROJ_PATH }}
          archive_output: true
